INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (2,
             21,
             'aaaadfdfd',
             2,
             '뉴미디어연구소',
             'Y',
             '2016-08-03 19:11:35.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (3,
             2,
             'd35c8fa9-7fe9-4820-accb-5dfa26b56689',
             2,
             '시너지개발부',
             'Y',
             '2016-08-08 11:30:43.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (5,
             3,
             '361a569f-34c3-4520-baf7-f0d32abae6a0',
             2,
             '시너지개발팀',
             'Y',
             '2016-08-08 19:11:20.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (6,
             2,
             '9c247a2d-77b1-457a-ba9b-43c972125ab6',
             2,
             '솔루션개발부',
             'Y',
             '2016-08-08 11:30:27.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (7,
             6,
             '0a3849ba-c180-47e7-8118-a037d6f3c4ba',
             2,
             '인터넷개발팀',
             'Y',
             '2016-08-05 19:14:57.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (8,
             6,
             'bc5e4a80-50a8-44b1-a71b-4e5c64ce724b',
             2,
             '모바일개발팀',
             'Y',
             '2016-08-04 17:14:07.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (10,
             2,
             'fe0fa567-fe30-4b16-92b8-6be075982b82',
             2,
             'NS개발부',
             'Y',
             '2016-08-05 13:51:06.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (11,
             10,
             '06e2f9aa-d74d-4fdb-bafb-03fbf2685d25',
             2,
             'NS개발팀',
             'Y',
             '2016-08-05 13:51:29.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (12,
             2,
             '1939ef1e-b45b-4427-8473-602f10189344',
             2,
             'CTS기술부',
             'Y',
             '2016-08-05 13:51:56.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (13,
             12,
             '4dea7638-2eae-4e6d-865c-111bd6bf6769',
             2,
             'CTS시스템팀',
             'Y',
             '2016-08-05 13:52:09.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (14,
             2,
             'b7bceead-35f2-465c-8b0d-e3819b1d622f',
             2,
             '미디어기술부',
             'Y',
             '2016-08-05 13:52:25.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (15,
             14,
             'c6a2df5d-7ca6-4071-8428-4a7f52443700',
             2,
             'IT시스템팀',
             'Y',
             '2016-08-05 13:52:37.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (16,
             14,
             '29088aea-c4da-4041-a6aa-907ae12e22ab',
             2,
             'IT협력팀',
             'Y',
             '2016-08-05 13:52:50.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (17,
             12,
             '63a60c5f-0037-4a0b-8b0d-6685fc6bcc67',
             2,
             '테스트',
             'D',
             '2016-08-09 13:24:41.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (18,
             21,
             '22ba2ef1-f771-48bb-99fb-3f6df4a3691a',
             2,
             '조선닷컴편집본부',
             'Y',
             '2016-08-09 11:26:22.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (19,
             18,
             '49f45cdb-17be-4bbc-97ee-4c60a653b8ab',
             2,
             '뉴스미디어부',
             'Y',
             '2016-08-09 11:26:56.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (20,
             22,
             'a5690ed4-b929-440b-a52f-b33759559df5',
             1,
             '경영기획실',
             'Y',
             '2016-08-09 13:20:24.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (21,
             0,
             'digital_chosunilbo',
             2,
             '디지틀조선일보',
             'Y',
             '2016-08-09 00:00:00.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (22,
             0,
             'chosunilbo',
             1,
             '조선일보',
             'Y',
             '2016-08-09 00:00:00.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (24,
             0,
             'a11f0a80-5e09-11e6-b356-00090ffe0001',
             6,
             'TV조선',
             'Y',
             '2016-08-09 17:18:53.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (25,
             24,
             'a61bda35-8e4d-4490-b0f2-d6af329ad046',
             6,
             '최상위부서',
             'Y',
             '2016-08-09 17:19:03.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (26,
             25,
             '93a0afb7-6bef-41a9-90f3-be47aabd966d',
             6,
             '그 아래 부서',
             'D',
             '2016-08-09 17:20:07.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (27,
             21,
             '5e5c5d61-611d-470d-b0b3-faab0fcf3a0d',
             2,
             '테스트',
             'D',
             '2016-08-19 16:41:05.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (28,
             21,
             '98b0465c-34de-49b9-b112-5cf1d5fd42cf',
             2,
             '테스트',
             'D',
             '2016-08-19 16:42:48.0');INSERT INTO departments(id,
                        pid,
                        deptid,
                        companyid,
                        name,
                        useyn,
                        lastmodified)
     VALUES (29,
             21,
             '1f035ee6-9a37-4cbc-9c61-9dea480b1e4e',
             2,
             '테스트',
             'D',
             '2016-08-19 16:45:22.0');COMMIT;